---
- name: Register output of 'sh run | incl enable secret'
  cisco.ios.ios_command:
    commands:
      - sh run | incl enable secret
  register: enable_secret_output

- name: Score 1.4.1 Set 'password' for 'enable secret'
  set_fact:
    enable_secret_score: "{{ 1 if enable_secret_output.stdout[0] != '' else 0 }}"

- name: Register output of 'sh run | incl service password-encryption'
  cisco.ios.ios_command:
    commands:
      - sh run | incl service password-encryption
  register: password_encryption_output

- name: Score 1.4.2 Enable 'service password-encryption'
  set_fact:
    password_encryption_score: >-
      {{
        1 if
          'service password-encryption' in password_encryption_output.stdout[0]
           and
           'no service password-encryption' not in password_encryption_output.stdout[0]
        else
          0
      }}

- name: Register output of 'show run | incl username'
  cisco.ios.ios_command:
    commands:
      - show run | incl username
  register: username_output

- name: Score 1.4.3 Set 'username secret' for all local users
  set_fact:
    encrypted_user_score: "{{ 0 if 'password' in username_output.stdout[0] else 1 }}"

- name: Display scores
  debug:
    msg:
      - "Enable Secret Score: {{ enable_secret_score }}"
      - "Password Encryption Score: {{ password_encryption_score }}"
      - "Encrypted Users Score: {{ encrypted_user_score }}"

- name: Calculate total score
  set_fact:
    total_score: >-
      {{
        enable_secret_score | int +
        password_encryption_score | int +
        encrypted_user_score | int
      }}

- name: Print the final total score
  debug:
    msg: "The total score is {{ total_score }}"
