---
- hosts: all_cisco_devices
  gather_facts: false
  become: true
  become_method: enable

  vars_files:
    - roles/cis_audit_role/vars/scores.yml

  tasks:
    - name: Retrieve the running configuration
      ios_command:
        commands: show running-config
      register: run_config_output

    - name: Check if 'aaa new-model' is enabled [1 point]
      set_fact:
        aaa_new_model_score: >-
          {{
            1 if 'aaa new-model' in run_config_output.stdout[0].splitlines() and
               not 'no aaa new-model' in run_config_output.stdout[0].splitlines()
            else 0
          }}

    - name: Check if 'aaa authentication login' is configured [1 point]
      set_fact:
        aaa_auth_login_score: 1
      when: "'aaa authentication login' in run_config_output.stdout[0]"

    - name: Check if 'aaa authentication enable' is configured [1 point]
      set_fact:
        aaa_auth_enable_score: 1
      when: "'aaa authentication enable' in run_config_output.stdout[0]"

    - name: Check if 'login authentication' is configured for line con 0
      set_fact:
        aaa_login_auth_line_con_0: >-
          {{
            1 if 'line con 0' in run_config_output.stdout[0] and
               'login authentication' in run_config_output.stdout[0].split('line con 0')[1].split('!')[0]
            else 0
          }}

    - name: Check if 'login authentication' is configured for line aux 0
      set_fact:
        aaa_login_auth_line_aux_0: >-
          {{
            1 if 'line aux 0' in run_config_output.stdout[0] and
               'login authentication' in run_config_output.stdout[0].split('line aux 0')[1].split('!')[0]
            else 0
          }}

    - name: Check if 'login authentication' is configured for VTY lines
      set_fact:
        aaa_login_auth_line_vty: >-
          {{
            1 if 'line vty 0 4' in run_config_output.stdout[0] and
              'login authentication' in run_config_output.stdout[0].split('line vty 0 4')[1].split('!')[0]
            else 0
          }}

    - name: Check if 'aaa accounting commands' is configured
      set_fact:
        aaa_accounting_commands_score: >-
          {{
            1 if 'aaa accounting commands' in ' '.join(run_config_output.stdout)
            else 0
          }}
    - name: Check if 'aaa accounting connection' is configured
      set_fact:
        aaa_accounting_connection_score: >-
          {{
            1 if 'aaa accounting connection' in ' '.join(run_config_output.stdout)
            else 0
          }}

    - name: Check if 'aaa accounting exec' is configured
      set_fact:
        aaa_accounting_exec_score: >-
          {{
            1 if 'aaa accounting exec' in ' '.join(run_config_output.stdout)
            else 0
          }}

    - name: Check if 'aaa accounting network' is configured
      set_fact:
        aaa_accounting_network_score: >-
          {{
            1 if 'aaa accounting network' in ' '.join(run_config_output.stdout)
            else 0
          }}

    - name: Check if 'aaa accounting system' is configured
      set_fact:
        aaa_accounting_system_score: >-
          {{
            1 if 'aaa accounting system' in ' '.join(run_config_output.stdout)
            else 0
          }}

    - name: Calculate total score
      set_fact:
        total_score: >-
          {{
            total_score | int +
            aaa_new_model_score | int +
            aaa_auth_login_score | int +
            aaa_auth_enable_score | int +
            aaa_login_auth_line_con_0 | int +
            aaa_login_auth_line_aux_0 | int +
            aaa_login_auth_line_vty | int +
            aaa_accounting_commands_score | int +
            aaa_accounting_connection_score | int +
            aaa_accounting_exec_score | int +
            aaa_accounting_network_score | int +
            aaa_accounting_system_score | int
          }}

    - name: Print the final total score
      debug:
        msg: "The final total score is {{ total_score }}"
