---
#playbook.yml
- name: Get running configuration from Cisco switches
  hosts: all_cisco_devices
  gather_facts: false  # We don't need to gather facts for this task
  become: true
  become_method: enable

  roles:
    - role: config_role
    - role: audit_role
  vars:
    ansible_become_pass: class

  vars_files:
    - audit_role/vars/scores.yml

  tasks:
    - name: AAA Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/aaa_config_playbook.yml

    - name: Access Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/access_rules_playbook.yml

    - name: Banner Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/banner_rules_playbook.yml

    - name: Password Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/password_rules_playbook.yml

    - name: SNMP Rules Configurations
      include_tasks: /root/cis_benchmark/configuration_role/tasks/snmp_rules_playbook.yml